const fs = require('fs');

// Read the SPA shell generated by the SPA mode build
let shellHtml = fs.readFileSync(
  'C:/Users/dandidce/Downloads/Master SRA Dasboard System/SRA Project Command Center/dist/client/_shell.html',
  'utf8'
);

// Fix all asset paths: /assets/ -> /commandcenter/assets/
shellHtml = shellHtml.replace(/"\/assets\//g, '"/commandcenter/assets/');

// Replace the existing $_TSR script with a minimal SPA-compatible one.
// The client needs:
//  1. window.$_TSR to exist (not null)
//  2. window.$_TSR.router to exist with matches array and lastMatchId
//  3. For SPA mode: matches can be minimal (just __root__) and isSpaMode flag
//
// The key insight: we want the router to know it's in SPA/CSR mode so it does
// createRoot instead of hydrateRoot. Setting matches to [] makes the router
// call matchRoutes() on the client location, which is the correct SPA behavior.
const spaInitScript = `<script>
// SPA mode bootstrap: provide minimal $_TSR so startClient skips SSR hydration
(function() {
  self.$R = self.$R || {};
  self.$R["tsr"] = [];
  self.$_TSR = {
    h() { this.hydrated = true; this.c(); },
    e() { this.streamEnded = true; this.c(); },
    c() {
      if (this.hydrated && this.streamEnded) {
        delete self.$_TSR;
        delete self.$R.tsr;
      }
    },
    p(fn) { this.initialized ? fn() : this.buffer.push(fn); },
    buffer: [],
    initialized: false
  };
  // Provide a minimal router state. matches=[] forces client to do its own
  // matchRoutes() from the current URL — correct SPA behavior.
  self.$_TSR.router = {
    manifest: { routes: { __root__: { preloads: [], scripts: [] } } },
    matches: [],
    lastMatchId: null
  };
  self.$_TSR.e();
})();
</script>`;

// Remove the old $_TSR stream barrier script
shellHtml = shellHtml.replace(
  /<script class="\$tsr"[^>]*>[\s\S]*?<\/script>/g,
  spaInitScript
);

fs.writeFileSync(
  'C:/Users/dandidce/Downloads/Master SRA Dasboard System/kiro/public/commandcenter/index.html',
  shellHtml
);

console.log('Done! index.html updated with SPA init script.');

// Verify
const badCount = (shellHtml.split('"/assets/').length - 1);
const goodCount = (shellHtml.split('"/commandcenter/assets/').length - 1);
console.log('Un-prefixed /assets/ refs:', badCount - goodCount);
console.log('/commandcenter/assets/ refs:', goodCount);
console.log('$_TSR replaced:', shellHtml.includes('SPA mode bootstrap'));
