/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVariationsRouteImport } from './routes/_authenticated/variations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRisksRouteImport } from './routes/_authenticated/risks'
import { Route as AuthenticatedQaqcRouteImport } from './routes/_authenticated/qaqc'
import { Route as AuthenticatedQaLabelsRouteImport } from './routes/_authenticated/qa-labels'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedPhotosRouteImport } from './routes/_authenticated/photos'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHseRouteImport } from './routes/_authenticated/hse'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDesignMonitoringRouteImport } from './routes/_authenticated/design-monitoring'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorrespondenceRouteImport } from './routes/_authenticated/correspondence'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminProfilesRouteImport } from './routes/_authenticated/admin-profiles'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedReportsWeeklyRouteImport } from './routes/_authenticated/reports/weekly'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports/monthly'
import { Route as AuthenticatedReportsFinalRouteImport } from './routes/_authenticated/reports/final'
import { Route as AuthenticatedReportsDailyRouteImport } from './routes/_authenticated/reports/daily'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as ApiPublicHooksOwnerDigestRouteImport } from './routes/api/public/hooks/owner-digest'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVariationsRoute = AuthenticatedVariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRisksRoute = AuthenticatedRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaqcRoute = AuthenticatedQaqcRouteImport.update({
  id: '/qaqc',
  path: '/qaqc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaLabelsRoute = AuthenticatedQaLabelsRouteImport.update({
  id: '/qa-labels',
  path: '/qa-labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotosRoute = AuthenticatedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHseRoute = AuthenticatedHseRouteImport.update({
  id: '/hse',
  path: '/hse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignMonitoringRoute =
  AuthenticatedDesignMonitoringRouteImport.update({
    id: '/design-monitoring',
    path: '/design-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorrespondenceRoute =
  AuthenticatedCorrespondenceRouteImport.update({
    id: '/correspondence',
    path: '/correspondence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProfilesRoute =
  AuthenticatedAdminProfilesRouteImport.update({
    id: '/admin-profiles',
    path: '/admin-profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsWeeklyRoute =
  AuthenticatedReportsWeeklyRouteImport.update({
    id: '/reports/weekly',
    path: '/reports/weekly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsFinalRoute =
  AuthenticatedReportsFinalRouteImport.update({
    id: '/reports/final',
    path: '/reports/final',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDailyRoute =
  AuthenticatedReportsDailyRouteImport.update({
    id: '/reports/daily',
    path: '/reports/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksOwnerDigestRoute =
  ApiPublicHooksOwnerDigestRouteImport.update({
    id: '/api/public/hooks/owner-digest',
    path: '/api/public/hooks/owner-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-profiles': typeof AuthenticatedAdminProfilesRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design-monitoring': typeof AuthenticatedDesignMonitoringRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hse': typeof AuthenticatedHseRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/qa-labels': typeof AuthenticatedQaLabelsRoute
  '/qaqc': typeof AuthenticatedQaqcRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/variations': typeof AuthenticatedVariationsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/final': typeof AuthenticatedReportsFinalRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/owner-digest': typeof ApiPublicHooksOwnerDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-profiles': typeof AuthenticatedAdminProfilesRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design-monitoring': typeof AuthenticatedDesignMonitoringRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hse': typeof AuthenticatedHseRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/qa-labels': typeof AuthenticatedQaLabelsRoute
  '/qaqc': typeof AuthenticatedQaqcRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/variations': typeof AuthenticatedVariationsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/final': typeof AuthenticatedReportsFinalRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/owner-digest': typeof ApiPublicHooksOwnerDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin-profiles': typeof AuthenticatedAdminProfilesRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/correspondence': typeof AuthenticatedCorrespondenceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design-monitoring': typeof AuthenticatedDesignMonitoringRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hse': typeof AuthenticatedHseRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/photos': typeof AuthenticatedPhotosRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/qa-labels': typeof AuthenticatedQaLabelsRoute
  '/_authenticated/qaqc': typeof AuthenticatedQaqcRoute
  '/_authenticated/risks': typeof AuthenticatedRisksRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/variations': typeof AuthenticatedVariationsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/_authenticated/reports/final': typeof AuthenticatedReportsFinalRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/owner-digest': typeof ApiPublicHooksOwnerDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin-profiles'
    | '/assistant'
    | '/contracts'
    | '/correspondence'
    | '/dashboard'
    | '/design-monitoring'
    | '/documents'
    | '/finance'
    | '/hse'
    | '/invoices'
    | '/meetings'
    | '/photos'
    | '/planning'
    | '/qa-labels'
    | '/qaqc'
    | '/risks'
    | '/settings'
    | '/variations'
    | '/api/chat'
    | '/projects/$projectId'
    | '/reports/daily'
    | '/reports/final'
    | '/reports/monthly'
    | '/reports/weekly'
    | '/projects/'
    | '/api/public/hooks/owner-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin-profiles'
    | '/assistant'
    | '/contracts'
    | '/correspondence'
    | '/dashboard'
    | '/design-monitoring'
    | '/documents'
    | '/finance'
    | '/hse'
    | '/invoices'
    | '/meetings'
    | '/photos'
    | '/planning'
    | '/qa-labels'
    | '/qaqc'
    | '/risks'
    | '/settings'
    | '/variations'
    | '/api/chat'
    | '/projects/$projectId'
    | '/reports/daily'
    | '/reports/final'
    | '/reports/monthly'
    | '/reports/weekly'
    | '/projects'
    | '/api/public/hooks/owner-digest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin-profiles'
    | '/_authenticated/assistant'
    | '/_authenticated/contracts'
    | '/_authenticated/correspondence'
    | '/_authenticated/dashboard'
    | '/_authenticated/design-monitoring'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/hse'
    | '/_authenticated/invoices'
    | '/_authenticated/meetings'
    | '/_authenticated/photos'
    | '/_authenticated/planning'
    | '/_authenticated/qa-labels'
    | '/_authenticated/qaqc'
    | '/_authenticated/risks'
    | '/_authenticated/settings'
    | '/_authenticated/variations'
    | '/api/chat'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/reports/daily'
    | '/_authenticated/reports/final'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/reports/weekly'
    | '/_authenticated/projects/'
    | '/api/public/hooks/owner-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksOwnerDigestRoute: typeof ApiPublicHooksOwnerDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/variations': {
      id: '/_authenticated/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof AuthenticatedVariationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risks': {
      id: '/_authenticated/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AuthenticatedRisksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qaqc': {
      id: '/_authenticated/qaqc'
      path: '/qaqc'
      fullPath: '/qaqc'
      preLoaderRoute: typeof AuthenticatedQaqcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa-labels': {
      id: '/_authenticated/qa-labels'
      path: '/qa-labels'
      fullPath: '/qa-labels'
      preLoaderRoute: typeof AuthenticatedQaLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photos': {
      id: '/_authenticated/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AuthenticatedPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hse': {
      id: '/_authenticated/hse'
      path: '/hse'
      fullPath: '/hse'
      preLoaderRoute: typeof AuthenticatedHseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-monitoring': {
      id: '/_authenticated/design-monitoring'
      path: '/design-monitoring'
      fullPath: '/design-monitoring'
      preLoaderRoute: typeof AuthenticatedDesignMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correspondence': {
      id: '/_authenticated/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof AuthenticatedCorrespondenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-profiles': {
      id: '/_authenticated/admin-profiles'
      path: '/admin-profiles'
      fullPath: '/admin-profiles'
      preLoaderRoute: typeof AuthenticatedAdminProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/weekly': {
      id: '/_authenticated/reports/weekly'
      path: '/reports/weekly'
      fullPath: '/reports/weekly'
      preLoaderRoute: typeof AuthenticatedReportsWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/final': {
      id: '/_authenticated/reports/final'
      path: '/reports/final'
      fullPath: '/reports/final'
      preLoaderRoute: typeof AuthenticatedReportsFinalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/daily': {
      id: '/_authenticated/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AuthenticatedReportsDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/owner-digest': {
      id: '/api/public/hooks/owner-digest'
      path: '/api/public/hooks/owner-digest'
      fullPath: '/api/public/hooks/owner-digest'
      preLoaderRoute: typeof ApiPublicHooksOwnerDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminProfilesRoute: typeof AuthenticatedAdminProfilesRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCorrespondenceRoute: typeof AuthenticatedCorrespondenceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignMonitoringRoute: typeof AuthenticatedDesignMonitoringRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHseRoute: typeof AuthenticatedHseRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedPhotosRoute: typeof AuthenticatedPhotosRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedQaLabelsRoute: typeof AuthenticatedQaLabelsRoute
  AuthenticatedQaqcRoute: typeof AuthenticatedQaqcRoute
  AuthenticatedRisksRoute: typeof AuthenticatedRisksRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVariationsRoute: typeof AuthenticatedVariationsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedReportsDailyRoute: typeof AuthenticatedReportsDailyRoute
  AuthenticatedReportsFinalRoute: typeof AuthenticatedReportsFinalRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedReportsWeeklyRoute: typeof AuthenticatedReportsWeeklyRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminProfilesRoute: AuthenticatedAdminProfilesRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCorrespondenceRoute: AuthenticatedCorrespondenceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignMonitoringRoute: AuthenticatedDesignMonitoringRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHseRoute: AuthenticatedHseRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedPhotosRoute: AuthenticatedPhotosRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedQaLabelsRoute: AuthenticatedQaLabelsRoute,
  AuthenticatedQaqcRoute: AuthenticatedQaqcRoute,
  AuthenticatedRisksRoute: AuthenticatedRisksRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVariationsRoute: AuthenticatedVariationsRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedReportsDailyRoute: AuthenticatedReportsDailyRoute,
  AuthenticatedReportsFinalRoute: AuthenticatedReportsFinalRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedReportsWeeklyRoute: AuthenticatedReportsWeeklyRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksOwnerDigestRoute: ApiPublicHooksOwnerDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
