/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpkRouteImport } from './routes/spk'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SpkRoute = SpkRouteImport.update({
  id: '/spk',
  path: '/spk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/clients': typeof ClientsRoute
  '/company': typeof CompanyRoute
  '/documents': typeof DocumentsRoute
  '/estimator': typeof EstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/spk': typeof SpkRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/clients': typeof ClientsRoute
  '/company': typeof CompanyRoute
  '/documents': typeof DocumentsRoute
  '/estimator': typeof EstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/spk': typeof SpkRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/clients': typeof ClientsRoute
  '/company': typeof CompanyRoute
  '/documents': typeof DocumentsRoute
  '/estimator': typeof EstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/portal': typeof PortalRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/spk': typeof SpkRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/clients'
    | '/company'
    | '/documents'
    | '/estimator'
    | '/invoices'
    | '/leads'
    | '/portal'
    | '/portfolio'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/spk'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/clients'
    | '/company'
    | '/documents'
    | '/estimator'
    | '/invoices'
    | '/leads'
    | '/portal'
    | '/portfolio'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/spk'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/clients'
    | '/company'
    | '/documents'
    | '/estimator'
    | '/invoices'
    | '/leads'
    | '/portal'
    | '/portfolio'
    | '/projects'
    | '/proposals'
    | '/reports'
    | '/spk'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  ClientsRoute: typeof ClientsRoute
  CompanyRoute: typeof CompanyRoute
  DocumentsRoute: typeof DocumentsRoute
  EstimatorRoute: typeof EstimatorRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  PortalRoute: typeof PortalRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  ProposalsRoute: typeof ProposalsRoute
  ReportsRoute: typeof ReportsRoute
  SpkRoute: typeof SpkRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spk': {
      id: '/spk'
      path: '/spk'
      fullPath: '/spk'
      preLoaderRoute: typeof SpkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  ClientsRoute: ClientsRoute,
  CompanyRoute: CompanyRoute,
  DocumentsRoute: DocumentsRoute,
  EstimatorRoute: EstimatorRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  PortalRoute: PortalRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  ProposalsRoute: ProposalsRoute,
  ReportsRoute: ReportsRoute,
  SpkRoute: SpkRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
